### ISSUE TITLE
Uncaught error in room name handling

### ISSUE THREAD

**Issue by ppwwyyxx** [MaskRay/wechatircd#15]
```
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aiohttp/server.py", line 285, in start
    yield from self.handle_request(message, payload)
  File "/usr/lib/python3.5/site-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/usr/bin/wechatircd", line 65, in handle_web_socket
    Server.instance.on_websocket(data)
  File "/usr/bin/wechatircd", line 1464, in on_websocket
    client.on_websocket(data)
  File "/usr/bin/wechatircd", line 1266, in on_websocket
    getattr(WeChatCommands, command)(self, data)
  File "/usr/bin/wechatircd", line 472, in room
    room = client.ensure_wechat_room(record)
  File "/usr/bin/wechatircd", line 1032, in ensure_wechat_room
    del self.name2wechat_room[irc_lower(room.name)]
KeyError: '&'
```

I have a chatroom whose name is consisting of emojis only. Maybe that's the cause.

**Comment by MaskRay** [comment]
[流浪] 求NYC住宿
