### ISSUE TITLE
aiohttp: No module named 'async_timeout'

### ISSUE THREAD

**Issue by myf** [MaskRay/wechatircd#27]
using python-aiohttp from aur version 1.2.0-2, wechatircd fails to start at
```
Traceback (most recent call last):
  File "/usr/bin/wechatircd", line 3, in <module>
    from aiohttp import web
  File "/usr/lib/python3.6/site-packages/aiohttp/__init__.py", line 11, in <module>
    from .connector import *  # noqa
  File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 18, in <module>
    from . import hdrs, helpers
  File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 19, in <module>
    from async_timeout import timeout
ModuleNotFoundError: No module named 'async_timeout'
```

**Comment by MaskRay** [comment]
Install `archlinuxcn/python-async_timeout` or `aur/python-async-timeout`. Take this as a grain of salt, I have not tested.

**Comment by myf** [comment]
thanks, this works. aiohttp version issue
